[graph]
targets = ["x86_64-pc-windows-msvc"]

[advisories]
ignore = []
yanked = "deny"
unmaintained = "all"
unsound = "all"

[licenses]
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
    "Unlicense",
]
confidence-threshold = 0.9
exceptions = [
    { allow = ["BSL-1.0"], crate = "clipboard-win" },
    { allow = ["BSL-1.0"], crate = "error-code" },
]

[licenses.private]
ignore = true

[bans]
multiple-versions = "deny"
wildcards = "deny"
highlight = "all"
skip = [{ crate = "windows-sys@0.60.2", reason = "arboard 3.6.1 pins windows-sys 0.60" }]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
